--- #环境分割线
server:
  port: 8000
  servlet:
    context-path: /
spring:
  profiles: prod
  datasource:
    #引入druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/jtdb?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: root
    
  application:   #定义服务名称,如果是多个相同的服务,那么名称必须相同,以便实现负载均衡
    name: provider-user #表示为user服务统称
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka
  instance:
    instance-id: provider-user-8000                #定义微服务的名称,每个具体的服务名称
    prefer-ip-address: true                        #是否显示IP和端口

#mybatis:
# type-aliases-package: com.jt.demo.pojo
#  mapper-locations: classpath:/mybatis/mappers/*.xml
  #开启驼峰映射
#  configuration:
#    map-underscore-to-camel-case: true
#mybatis-plush配置
mybatis-plus:
  type-aliases-package: com.jt.pojo
  mapper-locations: classpath:/mybatis/mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true  #自动开启驼峰规则映射
    
--- #环境分割线
server:
  port: 8005
  servlet:
    context-path: /
spring:
  profiles: test #该环境为测试环境
  datasource:
    #引入druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/jtdb?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: root
    
  application:   #定义服务名称,如果是多个相同的服务,那么名称必须相同,以便实现负载均衡
    name: provider-user #表示为user服务统称
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7000/eureka
  instance:
    instance-id: provider-user-8000                #定义微服务的名称,每个具体的服务名称
    prefer-ip-address: true                        #是否显示IP和端口

#mybatis:
# type-aliases-package: com.jt.demo.pojo
#  mapper-locations: classpath:/mybatis/mappers/*.xml
  #开启驼峰映射
#  configuration:
#    map-underscore-to-camel-case: true
#mybatis-plush配置
mybatis-plus:
  type-aliases-package: com.jt.pojo
  mapper-locations: classpath:/mybatis/mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true  #自动开启驼峰规则映射
  
  